name: Validate

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint pyyaml
    
    - name: Validate Python syntax
      run: |
        python -m py_compile datasync_setup_optimized.py
    
    - name: Validate YAML files
      run: |
        python -c "import yaml; yaml.safe_load(open('datasync-config.example.yaml'))"
    
    - name: Run pylint
      run: |
        pylint datasync_setup_optimized.py --disable=C0103,C0114,C0115,C0116 --max-line-length=100
      continue-on-error: true
